---
apiVersion: v1 
kind: Service
metadata:
  name: fb-clusterip-svc
  labels:
    app: facebook 

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32333
  selector:
    app: facebook 
    